name: statusbarz
description: A Flutter package for dynamically changing status bar color based
  on the background. Works with static colors and images.
version: 1.0.14
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/statusbarz
issue_tracker: https://github.com/Mankeli-Software/statusbarz/issues

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.0

dev_dependencies:
  dart_code_metrics: ^5.6.0
  flutter_test:
    sdk: flutter
  mankeli_analysis: ^1.1.0

flutter: null
