name: statusbarz
description: A Flutter package for dynamically changing status bar color based on the background. Works with static colors and images.
version: 1.0.10
homepage: https://mapventure.com
repository: https://github.com/Mapventure/statusbarz
issue_tracker: https://github.com/Mapventure/statusbarz/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
